### ISSUE TITLE
How can I make the Tilemap recognizes my "triagular pieces of tile"?

### ISSUE THREAD

**Issue by positivedivergent** [Unity-Technologies/2d-extras#164]
I have a set of tiles. But not all are square, some are triangular, and:

1- When I set use sprite as collider, Unity doesn make it exact, it sucks at it, creating it wiht "front steps" my char keep bumping and get stuck.

2- If I use the "rule tile", it just have a setup to put a game object in the tile (very expensive) and even with that, if my tile have variations, ex: A "square" top left corner piece can be changed to a  "triangular" top left corner piece, but "rule tile" can not put different game objects in the variations. So even making it expensive does not work.

3Q -So I started digging and realized that the "tile itself" does not have a "polygon collider" am I correct?

4aQ - Less expensive: So how can I tell the "TilemapCollider2D" of the tilemap that some pices have a perfect "rectangular triangle" collider to be generated? 

4bQ - More expensive: Or how can I change the "rule tile", so it accept a diferent gameobject to each variation?

5Q - Here's a loose question, have any tilemap with "ENTITY" tutorial released?

Thanks in advance!

**Comment by ChuanXin-Unity** [comment]
Hi,

1. The collider that is automatically generated is based on the outline of the Sprite. If you want to edit it, you can:

- Install the 2D Sprite Editor package from the Package Manager
- Select the Sprite asset in the Project Window
- From the menu, select "Window/2D/Sprite Editor"
- In the top-left corner of the Sprite Editor Window, select Custom Physics Shape from the dropdown button.
- Select the Sprite you want to edit and set the Physics Shape you want and apply the changes
- You may need to reset the TilemapCollider2D with the Sprites

2. Right now, you can have only a single GameObject per matching rule, but you could edit the script such that you can choose from multiple GameObjects. Otherwise, you could set a GameObject with multiple child GameObjects if you want more of them? If you can explain more about what you need with this, I can try to help more.

3. No, the Tile does not generate its own collider on a Tilemap with a PolygonCollider2D. You will need a TilemapCollider2D to generate colliders for each Tile.

4a. You will need to create the perfect triangle Physics Shape using the Sprite Editor in Q1. If the Sprite on the Tile has that Physics Shape, you will get the perfect triangle collider generated from the TilemapCollider2D.

4b. In RuleTile.cs, under GetTileData:

                    tileData.gameObject = rule.m_GameObject;

You could change this to other GameObjects here, and add more choices of GameObjects in each TilingRule as a start. Depending on how you want to choose your GameObjects, more places may need to be edited.

5. Sorry, unfortunately the answer is not at the moment as this is being worked on.

Let us know if you need more help!

**Comment by positivedivergent** [comment]
You were perfect in your answer.
