### ISSUE TITLE
Tilepalette/rule is just broken

### ISSUE THREAD

**Issue by Co-Verse** [Unity-Technologies/2d-extras#181]
At start I just configured a few rules, drag the asset onto the palette and start painting a tilemap... Unity freezes. Its memory usage skyrocketed and I needed to close it via the Task Manager. Now, with more rules, it runs at 2 fps in the scene view and creates a ton of "layer1" s in the palette window. My report here is mainly to ask... Can I keep the project believing that the 2D extras will work?

Also, can i send it as a Unity bug? With the project attached. Since it's a problem with a git package  I don't know if I should do that.

Sorry for the English, thanks.

**Comment by Varstahl** [comment]
Came here looking for a solution to the same thing. During the GGJ20 a few days ago we were working with RuleTiles to speed up prototyping. Then, a couple days with only barebones level and up to 40 tiles, we noticed huge performance hits, where the gameplay would start at, say, 60 fps and then with nothing happening keep dipping down.

So, basicaly, RuleTiles with just 10 rules and 40 tiles in a level ate up to 1200 FPS on a moderate PC, increasing system load constantly, making the game loop longer and longer and longer.

Same layer, same tiles, same physics with tiles applied manually instead of using RuleTiles, thousands of FPS came back. As it stands, it's just preposterous.

**Comment by johnsoncodehk** [comment]
Can you send me an example that can reproduce the problem? (Hope it's not my fault :P)

**Comment by Varstahl** [comment]
[Neusy/GGJ20@f75a18c](https://github.com/Neusy/GGJ20/tree/f75a18cb0a44b024be2f2a9a929937109721e7a7) this should be the last commit before we completely removed RuleTiles. I don't know exactly when we started noticing the problem and if at this point we already replaced the tiles manually, some other point in time like [this](https://github.com/Neusy/GGJ20/tree/eade43548a86f2eac4b172404cd02fda291fcdcf) might also help. And in any case it's pretty easy to make it worse, just select the RuleTile and paint a couple dozen squares.

Everything was done in the most updated 2019.3.

**Comment by Co-Verse** [comment]
I tried to reproduce the problem with new projects and it works fine most
of the time, except for this on. The only difference that i can think
between them is the order that I install the packages.


 Tilerule Problem.rar
<https://drive.google.com/file/d/1IvFfa5BIGKN2QyDWWddMYumhJoGXb65D/view?usp=drive_web>


Em ter., 4 de fev. de 2020 às 08:13, Bruno Passeri <notifications@github.com>
escreveu:

**Comment by johnsoncodehk** [comment]
@Varstahl First nice game :) The problem is because your have set the rule tile game object outputs to a Tilemap, and the Tilemap is using the rule tile too, final created game object is rises in geometric progression. Try to remove these game object outputs.

@Co-Verse Do you have a similar reason? If not can you give me a reproducible example?

**Comment by Co-Verse** [comment]
Yeah, it wasn't a Tilemap but it was definitely the problem, haha my bad.

**Comment by Varstahl** [comment]
> The problem is because your have set the rule tile game object outputs to a Tilemap, and the Tilemap is using the rule tile too, final created game object is rises in geometric progression. Try to remove these game object outputs.

Thought I followed instructions to a letter, but I'll check back, in the heat of the moment I or someone else could have done goofed. The explanation definitely rings true with what I experienced. Thanks for the pointer :)

**Comment by ChuanXin-Unity** [comment]
@johnsoncodehk Thank you for checking this out!
