### ISSUE TITLE
After I import this package 'ReorderableList' does not contain a definition for 'IsSelected' pop out

### ISSUE THREAD

**Issue by billy0204** [Unity-Technologies/2d-extras#282]
Library\PackageCache\com.unity.2d.tilemap.extras@da71076aeb\Editor\Tiles\RuleTile\RuleTileEditor.cs(277,26): error CS1061: 'ReorderableList' does not contain a definition for 'IsSelected' and no accessible extension method 'IsSelected' accepting a first argument of type 'ReorderableList' could be found (are you missing a using directive or an assembly reference?)

I am using 2020.3.8f1 with Windows, plz help me

**Comment by furrycombatwombat** [comment]
How did you fix this?

**Comment by Koopa1018** [comment]
@billy0204 -- having this problem too. Please share?

**Comment by ChuanXin-Unity** [comment]
https://github.com/Unity-Technologies/2d-extras/issues/280#issuecomment-842741404

Please do use the 2020.3 branch instead of the master branch. This branch is suitable for 2020.3.2 and above, and will not have the issue you experienced. If you are using other versions of the Unity Editor, please use the corresponding branch instead.

Hope this helps!

**Comment by Koopa1018** [comment]
Ahh, gotcha.

Wondered if I might just need to upgrade Unity :)
