### ISSUE TITLE
Create tags/releases for version targeted at specific unity versions 

### ISSUE THREAD

**Issue by SundeepK** [Unity-Technologies/2d-extras#92]
This issue is simple to resolve. I think we should be using tags or releases for version supported by specific unity versions. I think it will make life a little easier to track versions allowing to create multiple versions for the same unity version as well. I also think it's a little more initiative than checking out a branch.

**Comment by ChuanXin-Unity** [comment]
Hi, I am not familiar with the tag system, but it sounds like it could be useful. I assume you would change between versions through the tag?

**Comment by sundeepkalt** [comment]
Yes thats how it would be used. Here some docs around this https://git-scm.com/book/en/v2/Git-Basics-Tagging.

For example, we can checkout tag that works with specific unity version, which is nice because most people probably don't want to make changes to existing code and the tag would basically be an immutable point in time for us.

**Comment by ChuanXin-Unity** [comment]
That sounds fair! We will try it using this out. Thanks!
